name: Test packages/discord-types
on:
    pull_request:
        paths:
            - packages/discord-types/**
    push:
        paths:
            - packages/discord-types/**
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: ^20.11.0
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check packages/discord-types for TypeScript errors and lint
              run: |
                  cd packages/discord-types
                  pnpm test

            - name: Check if packages/discord-types is compatible with Vencord
              run: pnpm testTsc
